application: rlopes-blog
version: 1
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (.git)|
 (#.*#)|
 (.*~)
 (.*/.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (README)
 )$
 
handlers:
- url: /static
  static_dir: static    
  
- url: .*
  script: main.py
